### ISSUE TITLE
set html and body height to 100%

### ISSUE THREAD

**Issue by mef** [skeleton-framework/skeleton-framework#38]
Having the height of `body` equal to 100% of the page is necessary to set height of children elements. How about setting these by default inside skeleton-framework?

````css
html {
  height: 100%;
}
body {
  min-height: 100%;
}
````

as in this [stackOverflow answer](http://stackoverflow.com/a/6654996/1006854).
